rmarkdown::render("index.Rmd")
system("git checkout gh-pages")
system("git add index.html")
system("git commit -m 'fresh render on index.html'")
system("git push origin gh-pages")
system("git checkout master")
system("git add index.Rmd")
system("git commit -m 'fresh render on index.Rmd'")
system("git push origin master")